spring.application.name=TAHub
spring.datasource.url=jdbc:postgresql://localhost:5433/tahub
spring.datasource.username=tahub
spring.datasource.password=tahub123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true